all:
	pdflatex thesis-main
	pdflatex thesis-main
	bibtex thesis-main
	pdflatex thesis-main
	pdflatex thesis-main

clean:
	rm -f *.aux 
	rm -f *.dvi
	rm -f *.fdb_latexmk
	rm -f *.fls
	rm -f *.log
	rm -f *.lof
	rm -f *.out
	rm -f *.toc
	rm -f *.bbl
	rm -f *.blg
